import os
import sys
from datetime import datetime
from pymongo import MongoClient, ASCENDING

# Ensure backend directory is in the path to import local modules
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.core.config import settings

def seed_templates():
    print("Connecting to MongoDB...")
    client = MongoClient(settings.MONGODB_URI)
    db = client[settings.DATABASE_NAME]
    collection = db.resume_templates

    print("Creating indexes on resume_templates...")
    collection.create_index([("templateId", ASCENDING)], unique=True)
    collection.create_index([("slug", ASCENDING)], unique=True)
    collection.create_index([("category", ASCENDING)])
    collection.create_index([("displayOrder", ASCENDING)])

    # Define all 20 templates
    templates = [
        # --- Professional ---
        {
            "templateId": "classic_professional",
            "name": "Classic Professional",
            "slug": "classic-professional",
            "category": "Professional",
            "description": "Traditional ATS-friendly layout optimized for experienced corporate professionals.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/classic_professional_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/classic_professional_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/classic_professional_cover.jpg",
            "atsFriendly": True,
            "atsScore": 99,
            "featured": True,
            "premium": False,
            "recommendedFor": ["Executives", "Managers", "Corporate Leaders"],
            "industry": ["Finance", "Consulting", "Operations", "Legal"],
            "colors": {"primary": "#1E293B", "secondary": "#475569"},
            "font": {"family": "Times-Roman", "heading": 16, "body": 10},
            "layout": {"columns": 1, "header": "top", "spacing": 12, "margin": 36},
            "sections": ["header", "summary", "experience", "education", "skills", "certifications"],
            "renderer": "classicProfessional",
            "enabled": True,
            "displayOrder": 1
        },
        {
            "templateId": "modern_professional",
            "name": "Modern Professional",
            "slug": "modern-professional",
            "category": "Professional",
            "description": "Clean, structured template with modern accent tones for contemporary job seekers.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/modern_professional_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/modern_professional_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/modern_professional_cover.jpg",
            "atsFriendly": True,
            "atsScore": 96,
            "featured": True,
            "premium": False,
            "recommendedFor": ["Mid-level Engineers", "Project Managers", "Sales Leaders"],
            "industry": ["Technology", "Sales", "Healthcare", "Real Estate"],
            "colors": {"primary": "#0F172A", "secondary": "#2563EB"},
            "font": {"family": "Helvetica", "heading": 15, "body": 10},
            "layout": {"columns": 1, "header": "left-accent", "spacing": 14, "margin": 32},
            "sections": ["header", "summary", "experience", "projects", "skills", "education"],
            "renderer": "modernProfessional",
            "enabled": True,
            "displayOrder": 2
        },
        {
            "templateId": "timeless_professional",
            "name": "Timeless Professional",
            "slug": "timeless-professional",
            "category": "Professional",
            "description": "Elegant serif header alignment conveying stability, expertise, and authority.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/timeless_professional_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/timeless_professional_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/timeless_professional_cover.jpg",
            "atsFriendly": True,
            "atsScore": 95,
            "featured": False,
            "premium": False,
            "recommendedFor": ["Directors", "Academic Researchers", "Architects"],
            "industry": ["Education", "Engineering", "Real Estate", "Law"],
            "colors": {"primary": "#1A1A1A", "secondary": "#6B7280"},
            "font": {"family": "Times-Roman", "heading": 18, "body": 11},
            "layout": {"columns": 1, "header": "center", "spacing": 15, "margin": 40},
            "sections": ["header", "summary", "experience", "education", "publications", "skills"],
            "renderer": "timelessProfessional",
            "enabled": True,
            "displayOrder": 3
        },
        {
            "templateId": "executive_professional",
            "name": "Executive Professional",
            "slug": "executive-professional",
            "category": "Professional",
            "description": "Bold header panel showcasing critical metrics, vision, and executive summary.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/executive_professional_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/executive_professional_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/executive_professional_cover.jpg",
            "atsFriendly": True,
            "atsScore": 98,
            "featured": False,
            "premium": True,
            "recommendedFor": ["C-Suite Executives", "VPs", "Senior Directors"],
            "industry": ["Enterprise", "Banking", "Fintech", "Consulting"],
            "colors": {"primary": "#312E81", "secondary": "#4338CA"},
            "font": {"family": "Helvetica", "heading": 16, "body": 10},
            "layout": {"columns": 1, "header": "top-split", "spacing": 12, "margin": 36},
            "sections": ["header", "summary", "experience", "education", "key_metrics", "skills"],
            "renderer": "executiveProfessional",
            "enabled": True,
            "displayOrder": 4
        },
        {
            "templateId": "corporate_professional",
            "name": "Corporate Professional",
            "slug": "corporate-professional",
            "category": "Professional",
            "description": "Ultra-reliable layout designed according to standard global corporate recruiter expectations.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/corporate_professional_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/corporate_professional_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/corporate_professional_cover.jpg",
            "atsFriendly": True,
            "atsScore": 97,
            "featured": False,
            "premium": False,
            "recommendedFor": ["Consultants", "Financial Analysts", "Accountants"],
            "industry": ["Corporate Services", "Advisory", "Accounting", "HR"],
            "colors": {"primary": "#0F172A", "secondary": "#334155"},
            "font": {"family": "Helvetica", "heading": 14, "body": 9},
            "layout": {"columns": 1, "header": "standard", "spacing": 10, "margin": 32},
            "sections": ["header", "summary", "experience", "education", "skills", "certifications"],
            "renderer": "corporateProfessional",
            "enabled": True,
            "displayOrder": 5
        },
        # --- Student ---
        {
            "templateId": "modern_student",
            "name": "Modern Student",
            "slug": "modern-student",
            "category": "Student",
            "description": "Vibrant template highlighting academic projects, club leadership, and coursework.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/modern_student_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/modern_student_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/modern_student_cover.jpg",
            "atsFriendly": True,
            "atsScore": 92,
            "featured": True,
            "premium": False,
            "recommendedFor": ["Undergraduates", "Graduates", "Internship Seekers"],
            "industry": ["Technology", "Creative", "Marketing", "Business"],
            "colors": {"primary": "#0284C7", "secondary": "#0F172A"},
            "font": {"family": "Helvetica", "heading": 14, "body": 10},
            "layout": {"columns": 1, "header": "top-centered", "spacing": 12, "margin": 30},
            "sections": ["header", "education", "projects", "experience", "skills", "achievements"],
            "renderer": "modernStudent",
            "enabled": True,
            "displayOrder": 6
        },
        {
            "templateId": "business_undergraduate",
            "name": "Business Undergraduate",
            "slug": "business-undergraduate",
            "category": "Student",
            "description": "Polished layout emphasizing leadership, case competitions, and business associations.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/business_undergraduate_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/business_undergraduate_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/business_undergraduate_cover.jpg",
            "atsFriendly": True,
            "atsScore": 94,
            "featured": False,
            "premium": False,
            "recommendedFor": ["MBA Students", "Finance Majors", "Consulting Hopefuls"],
            "industry": ["Management", "Investment Banking", "Advisory", "Business Development"],
            "colors": {"primary": "#1E3A8A", "secondary": "#1E40AF"},
            "font": {"family": "Times-Roman", "heading": 15, "body": 10},
            "layout": {"columns": 1, "header": "classic-top", "spacing": 14, "margin": 36},
            "sections": ["header", "education", "experience", "projects", "activities", "skills"],
            "renderer": "businessUndergraduate",
            "enabled": True,
            "displayOrder": 7
        },
        {
            "templateId": "computer_science_student",
            "name": "Computer Science Student",
            "slug": "computer-science-student",
            "category": "Student",
            "description": "Tech-focused outline with dedicated columns for programming languages and technical projects.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/computer_science_student_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/computer_science_student_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/computer_science_student_cover.jpg",
            "atsFriendly": True,
            "atsScore": 98,
            "featured": True,
            "premium": False,
            "recommendedFor": ["CS Majors", "Software Engineering Interns", "Web Developers"],
            "industry": ["IT", "Software Development", "DevOps"],
            "colors": {"primary": "#0F172A", "secondary": "#475569"},
            "font": {"family": "Helvetica", "heading": 13, "body": 9},
            "layout": {"columns": 1, "header": "compact", "spacing": 8, "margin": 28},
            "sections": ["header", "education", "skills", "projects", "experience", "certifications"],
            "renderer": "computerScienceStudent",
            "enabled": True,
            "displayOrder": 8
        },
        {
            "templateId": "ai_engineer_student",
            "name": "AI Engineer Student",
            "slug": "ai-engineer-student",
            "category": "Student",
            "description": "Highlight research publications, deep learning models, Kaggle achievements, and GPU clusters.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/ai_engineer_student_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/ai_engineer_student_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/ai_engineer_student_cover.jpg",
            "atsFriendly": True,
            "atsScore": 99,
            "featured": True,
            "premium": True,
            "recommendedFor": ["AI Engineers", "Data Scientists", "Research Assistants"],
            "industry": ["AI/ML", "Big Data", "Robotics", "Analytics"],
            "colors": {"primary": "#4F46E5", "secondary": "#06B6D4"},
            "font": {"family": "Helvetica", "heading": 14, "body": 10},
            "layout": {"columns": 1, "header": "tech-left", "spacing": 12, "margin": 32},
            "sections": ["header", "education", "research", "projects", "skills", "awards"],
            "renderer": "aiEngineerStudent",
            "enabled": True,
            "displayOrder": 9
        },
        {
            "templateId": "fresher_zero_experience",
            "name": "Fresher Zero Experience",
            "slug": "fresher-zero-experience",
            "category": "Student",
            "description": "Designed to maximize space using coursework, extracurriculars, volunteer work, and soft skills.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/fresher_zero_experience_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/fresher_zero_experience_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/fresher_zero_experience_cover.jpg",
            "atsFriendly": True,
            "atsScore": 90,
            "featured": False,
            "premium": False,
            "recommendedFor": ["High School Graduates", "First-year Students", "Volunteers"],
            "industry": ["Retail", "Customer Service", "General Entry-level"],
            "colors": {"primary": "#374151", "secondary": "#4B5563"},
            "font": {"family": "Helvetica", "heading": 14, "body": 11},
            "layout": {"columns": 1, "header": "soft-top", "spacing": 16, "margin": 36},
            "sections": ["header", "education", "activities", "projects", "skills", "languages"],
            "renderer": "fresherZeroExperience",
            "enabled": True,
            "displayOrder": 10
        },
        # --- Minimal ---
        {
            "templateId": "minimalist_expert",
            "name": "Minimalist Expert",
            "slug": "minimalist-expert",
            "category": "Minimal",
            "description": "Ultra-clean black and white design focusing purely on core text and layout readability.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/minimalist_expert_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/minimalist_expert_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/minimalist_expert_cover.jpg",
            "atsFriendly": True,
            "atsScore": 99,
            "featured": False,
            "premium": False,
            "recommendedFor": ["Senior Consultants", "Writers", "Minimalist Designers"],
            "industry": ["Design", "Publishing", "Consulting"],
            "colors": {"primary": "#000000", "secondary": "#555555"},
            "font": {"family": "Helvetica", "heading": 14, "body": 10},
            "layout": {"columns": 1, "header": "clean-top", "spacing": 12, "margin": 40},
            "sections": ["header", "summary", "experience", "education", "skills"],
            "renderer": "minimalistExpert",
            "enabled": True,
            "displayOrder": 11
        },
        {
            "templateId": "clean_resume",
            "name": "Clean Resume",
            "slug": "clean-resume",
            "category": "Minimal",
            "description": "Minimal design with subtle grid alignments and muted blue headers.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/clean_resume_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/clean_resume_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/clean_resume_cover.jpg",
            "atsFriendly": True,
            "atsScore": 96,
            "featured": True,
            "premium": False,
            "recommendedFor": ["Marketing Analysts", "Operations Staff", "Administrators"],
            "industry": ["Operations", "Administration", "Customer Success"],
            "colors": {"primary": "#1E293B", "secondary": "#3B82F6"},
            "font": {"family": "Helvetica", "heading": 14, "body": 10},
            "layout": {"columns": 1, "header": "clean-accent", "spacing": 14, "margin": 32},
            "sections": ["header", "summary", "experience", "education", "skills", "certifications"],
            "renderer": "cleanResume",
            "enabled": True,
            "displayOrder": 12
        },
        {
            "templateId": "ats_classic",
            "name": "ATS Classic",
            "slug": "ats-classic",
            "category": "Minimal",
            "description": "Classic single-column serif template modeled after verified Ivy League formats.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/ats_classic_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/ats_classic_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/ats_classic_cover.jpg",
            "atsFriendly": True,
            "atsScore": 99,
            "featured": True,
            "premium": False,
            "recommendedFor": ["Investment Bankers", "Data Engineers", "Lawyers"],
            "industry": ["Investment Banking", "Legal", "Information Technology"],
            "colors": {"primary": "#111111", "secondary": "#222222"},
            "font": {"family": "Times-Roman", "heading": 16, "body": 11},
            "layout": {"columns": 1, "header": "centered-header", "spacing": 10, "margin": 36},
            "sections": ["header", "education", "experience", "projects", "skills"],
            "renderer": "atsClassic",
            "enabled": True,
            "displayOrder": 13
        },
        {
            "templateId": "ats_modern",
            "name": "ATS Modern",
            "slug": "ats-modern",
            "category": "Minimal",
            "description": "A modern sans-serif update to the classic ATS layout, featuring compact spacers.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/ats_modern_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/ats_modern_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/ats_modern_cover.jpg",
            "atsFriendly": True,
            "atsScore": 99,
            "featured": True,
            "premium": False,
            "recommendedFor": ["Cloud Architects", "Cybersecurity Experts", "Data Analysts"],
            "industry": ["Cybersecurity", "Cloud Computing", "Systems Administration"],
            "colors": {"primary": "#0F172A", "secondary": "#334155"},
            "font": {"family": "Helvetica", "heading": 15, "body": 10},
            "layout": {"columns": 1, "header": "left-aligned-header", "spacing": 11, "margin": 32},
            "sections": ["header", "experience", "projects", "education", "skills", "certifications"],
            "renderer": "atsModern",
            "enabled": True,
            "displayOrder": 14
        },
        # --- International ---
        {
            "templateId": "harvard_style",
            "name": "Harvard Style",
            "slug": "harvard",
            "category": "International",
            "description": "Premium Harvard Business School layout. Single column, Times New Roman, bold section dividers.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/harvard_style_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/harvard_style_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/harvard_style_cover.jpg",
            "atsFriendly": True,
            "atsScore": 99,
            "featured": True,
            "premium": False,
            "recommendedFor": ["MBA Grads", "Investment Bankers", "Top Tier Consultants"],
            "industry": ["Strategy Consulting", "Investment Banking", "Corporate Finance"],
            "colors": {"primary": "#A51C30", "secondary": "#111111"},
            "font": {"family": "Times-Roman", "heading": 14, "body": 10},
            "layout": {"columns": 1, "header": "harvard-header", "spacing": 12, "margin": 40},
            "sections": ["header", "education", "experience", "projects", "additional_info"],
            "renderer": "harvardStyle",
            "enabled": True,
            "displayOrder": 15
        },
        {
            "templateId": "stanford_style",
            "name": "Stanford Style",
            "slug": "stanford",
            "category": "International",
            "description": "Distinguished Stanford Graduate School of Business format with clean horizontal dividers.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/stanford_style_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/stanford_style_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/stanford_style_cover.jpg",
            "atsFriendly": True,
            "atsScore": 99,
            "featured": True,
            "premium": False,
            "recommendedFor": ["Silicon Valley Entrants", "Tech Product Managers", "VC Associates"],
            "industry": ["Venture Capital", "Product Management", "Tech Startups"],
            "colors": {"primary": "#8C1515", "secondary": "#2E2D29"},
            "font": {"family": "Helvetica", "heading": 15, "body": 10},
            "layout": {"columns": 1, "header": "stanford-header", "spacing": 14, "margin": 40},
            "sections": ["header", "experience", "education", "projects", "skills"],
            "renderer": "stanfordStyle",
            "enabled": True,
            "displayOrder": 16
        },
        # --- Industry ---
        {
            "templateId": "software_engineer",
            "name": "Software Engineer",
            "slug": "software-engineer",
            "category": "Industry",
            "description": "Engineered layout presenting GitHub links, technical stack, core systems, and code contributions.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/software_engineer_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/software_engineer_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/software_engineer_cover.jpg",
            "atsFriendly": True,
            "atsScore": 99,
            "featured": True,
            "premium": False,
            "recommendedFor": ["Backend Developers", "Full Stack Engineers", "SREs"],
            "industry": ["Technology", "Software Engineering", "Telecommunications"],
            "colors": {"primary": "#0369A1", "secondary": "#334155"},
            "font": {"family": "Helvetica", "heading": 14, "body": 10},
            "layout": {"columns": 1, "header": "dev-top", "spacing": 10, "margin": 32},
            "sections": ["header", "skills", "experience", "projects", "education"],
            "renderer": "softwareEngineer",
            "enabled": True,
            "displayOrder": 17
        },
        {
            "templateId": "social_work",
            "name": "Social Work",
            "slug": "social-work",
            "category": "Industry",
            "description": "Warm, communication-centric structure optimized for counseling, community work, and NGO sectors.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/social_work_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/social_work_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/social_work_cover.jpg",
            "atsFriendly": True,
            "atsScore": 95,
            "featured": False,
            "premium": False,
            "recommendedFor": ["Social Workers", "Therapists", "NGO Program Leads"],
            "industry": ["Healthcare", "Non-profit", "Social Services"],
            "colors": {"primary": "#047857", "secondary": "#111827"},
            "font": {"family": "Helvetica", "heading": 14, "body": 10},
            "layout": {"columns": 1, "header": "warm-top", "spacing": 12, "margin": 36},
            "sections": ["header", "summary", "experience", "education", "volunteer_work", "skills"],
            "renderer": "socialWork",
            "enabled": True,
            "displayOrder": 18
        },
        {
            "templateId": "marketing_professional",
            "name": "Marketing Professional",
            "slug": "marketing-professional",
            "category": "Industry",
            "description": "Highlights key campaigns, marketing analytics, SEO conversions, and visual design competencies.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/marketing_professional_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/marketing_professional_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/marketing_professional_cover.jpg",
            "atsFriendly": True,
            "atsScore": 93,
            "featured": False,
            "premium": True,
            "recommendedFor": ["Marketing Managers", "Brand Strategists", "Growth Hackers"],
            "industry": ["Marketing", "E-commerce", "Advertising"],
            "colors": {"primary": "#BE185D", "secondary": "#4D002B"},
            "font": {"family": "Helvetica", "heading": 15, "body": 10},
            "layout": {"columns": 1, "header": "marketing-top", "spacing": 13, "margin": 32},
            "sections": ["header", "summary", "experience", "projects", "skills", "education"],
            "renderer": "marketingProfessional",
            "enabled": True,
            "displayOrder": 19
        },
        {
            "templateId": "finance_professional",
            "name": "Finance Professional",
            "slug": "finance-professional",
            "category": "Industry",
            "description": "Emphasizes portfolio sizes, transactional history, modeling capabilities, and risk analysis.",
            "previewImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/finance_professional_preview.jpg",
            "thumbnail": "https://res.cloudinary.com/demo/image/upload/v1625070000/finance_professional_thumb.jpg",
            "coverImage": "https://res.cloudinary.com/demo/image/upload/v1625070000/finance_professional_cover.jpg",
            "atsFriendly": True,
            "atsScore": 97,
            "featured": False,
            "premium": False,
            "recommendedFor": ["Risk Officers", "Finance Directors", "Valuation Experts"],
            "industry": ["Banking", "Wealth Management", "Corporate Finance"],
            "colors": {"primary": "#0F172A", "secondary": "#1E3A8A"},
            "font": {"family": "Times-Roman", "heading": 14, "body": 9},
            "layout": {"columns": 1, "header": "finance-clean", "spacing": 11, "margin": 34},
            "sections": ["header", "summary", "experience", "education", "skills", "certifications"],
            "renderer": "financeProfessional",
            "enabled": True,
            "displayOrder": 20
        }
    ]

    print("Seeding templates...")
    now = datetime.utcnow()
    inserted_count = 0
    updated_count = 0

    for temp in templates:
        temp["createdAt"] = now
        temp["updatedAt"] = now
        temp["usageCount"] = temp.get("usageCount", 0)
        temp["downloadCount"] = temp.get("downloadCount", 0)

        # Check if exists by templateId
        existing = collection.find_one({"templateId": temp["templateId"]})
        if existing:
            # Update key configurations, retaining usage logs/metadata
            temp.pop("createdAt", None)  # Preserve original createdAt
            collection.update_one({"templateId": temp["templateId"]}, {"$set": temp})
            updated_count += 1
        else:
            collection.insert_one(temp)
            inserted_count += 1

    print(f"Database seed complete! Inserted: {inserted_count}, Updated: {updated_count}")

if __name__ == "__main__":
    seed_templates()
