"""Initial schema setup

Revision ID: 4b35632a5794
Revises: 
Create Date: 2026-07-11 15:16:42.452892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b35632a5794'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_prompts_feature'), table_name='ai_prompts')
    op.drop_index(op.f('ix_ai_prompts_id'), table_name='ai_prompts')
    op.drop_table('ai_prompts')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_ai_system_settings_id'), table_name='ai_system_settings')
    op.drop_table('ai_system_settings')
    op.drop_index(op.f('ix_career_readiness_id'), table_name='career_readiness')
    op.drop_table('career_readiness')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_ai_gateway_logs_id'), table_name='ai_gateway_logs')
    op.drop_table('ai_gateway_logs')
    op.drop_index(op.f('ix_resume_templates_id'), table_name='resume_templates')
    op.drop_index(op.f('ix_resume_templates_slug'), table_name='resume_templates')
    op.drop_table('resume_templates')
    op.drop_index(op.f('ix_editing_sessions_id'), table_name='editing_sessions')
    op.drop_table('editing_sessions')
    op.drop_index(op.f('ix_ai_providers_id'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_name'), table_name='ai_providers')
    op.drop_index(op.f('ix_ai_providers_slug'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_resume_master_id'), table_name='resume_master')
    op.drop_table('resume_master')
    op.drop_index(op.f('ix_resume_downloads_id'), table_name='resume_downloads')
    op.drop_table('resume_downloads')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_ai_models_feature'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_resume_experience_id'), table_name='resume_experience')
    op.drop_table('resume_experience')
    op.drop_index(op.f('ix_login_history_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_resume_ats_id'), table_name='resume_ats')
    op.drop_table('resume_ats')
    op.drop_index(op.f('ix_download_logs_id'), table_name='download_logs')
    op.drop_table('download_logs')
    op.drop_index(op.f('ix_resume_skills_id'), table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_backups_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_resume_ai_logs_id'), table_name='resume_ai_logs')
    op.drop_table('resume_ai_logs')
    op.drop_index(op.f('ix_system_health_id'), table_name='system_health')
    op.drop_table('system_health')
    op.drop_index(op.f('ix_resume_studio_versions_id'), table_name='resume_studio_versions')
    op.drop_table('resume_studio_versions')
    op.drop_index(op.f('ix_ai_usage_logs_id'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_day'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_resume_versions_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_resume_education_id'), table_name='resume_education')
    op.drop_table('resume_education')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_resume_certificates_id'), table_name='resume_certificates')
    op.drop_table('resume_certificates')
    op.drop_index(op.f('ix_dataset_imports_id'), table_name='dataset_imports')
    op.drop_table('dataset_imports')
    op.drop_index(op.f('ix_resume_projects_id'), table_name='resume_projects')
    op.drop_table('resume_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('tech_stack', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('duration', sa.VARCHAR(), nullable=True),
    sa.Column('github_link', sa.VARCHAR(), nullable=True),
    sa.Column('live_demo', sa.VARCHAR(), nullable=True),
    sa.Column('achievements', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_projects_id'), 'resume_projects', ['id'], unique=False)
    op.create_table('dataset_imports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('import_type', sa.VARCHAR(), nullable=True),
    sa.Column('total_records', sa.INTEGER(), nullable=True),
    sa.Column('imported_count', sa.INTEGER(), nullable=True),
    sa.Column('updated_count', sa.INTEGER(), nullable=True),
    sa.Column('skipped_count', sa.INTEGER(), nullable=True),
    sa.Column('failed_count', sa.INTEGER(), nullable=True),
    sa.Column('rollback_status', sa.VARCHAR(), nullable=True),
    sa.Column('imported_rolls', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_imports_id'), 'dataset_imports', ['id'], unique=False)
    op.create_table('resume_certificates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('organization', sa.VARCHAR(), nullable=False),
    sa.Column('issue_date', sa.VARCHAR(), nullable=True),
    sa.Column('credential_id', sa.VARCHAR(), nullable=True),
    sa.Column('credential_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_certificates_id'), 'resume_certificates', ['id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('pinned', sa.BOOLEAN(), nullable=True),
    sa.Column('attachment_pdf', sa.VARCHAR(), nullable=True),
    sa.Column('attachment_image', sa.VARCHAR(), nullable=True),
    sa.Column('target_audience', sa.VARCHAR(), nullable=True),
    sa.Column('target_value', sa.VARCHAR(), nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(), nullable=True),
    sa.Column('read_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_username', sa.VARCHAR(), nullable=False),
    sa.Column('operation', sa.VARCHAR(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('browser', sa.VARCHAR(), nullable=True),
    sa.Column('device', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('affected_record', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('purpose', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_table('resume_education',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('institution', sa.VARCHAR(), nullable=False),
    sa.Column('degree', sa.VARCHAR(), nullable=False),
    sa.Column('board', sa.VARCHAR(), nullable=True),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.Column('cgpa', sa.FLOAT(), nullable=True),
    sa.Column('passing_year', sa.INTEGER(), nullable=False),
    sa.Column('achievements', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_education_id'), 'resume_education', ['id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('ats_score', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_id'), 'resume_versions', ['id'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.VARCHAR(), nullable=False),
    sa.Column('requests', sa.INTEGER(), nullable=True),
    sa.Column('tokens', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_id'), 'ai_usage', ['id'], unique=False)
    op.create_index(op.f('ix_ai_usage_day'), 'ai_usage', ['day'], unique=1)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(), nullable=False),
    sa.Column('time_saved_minutes', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_id'), 'ai_usage_logs', ['id'], unique=False)
    op.create_table('resume_studio_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.Column('ats_score', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_studio_versions_id'), 'resume_studio_versions', ['id'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cpu_usage', sa.FLOAT(), nullable=True),
    sa.Column('ram_usage', sa.FLOAT(), nullable=True),
    sa.Column('disk_usage', sa.FLOAT(), nullable=True),
    sa.Column('db_health', sa.VARCHAR(), nullable=True),
    sa.Column('api_health', sa.VARCHAR(), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('db_queries_count', sa.INTEGER(), nullable=True),
    sa.Column('request_rate', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_id'), 'system_health', ['id'], unique=False)
    op.create_table('resume_ai_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(), nullable=False),
    sa.Column('prompt_used', sa.TEXT(), nullable=True),
    sa.Column('response_received', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_ai_logs_id'), 'resume_ai_logs', ['id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('template', sa.VARCHAR(), nullable=True),
    sa.Column('personal_info_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('summary_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('experience_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('education_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('skills_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('projects_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('certifications_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('languages_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('achievements_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('ats_score', sa.INTEGER(), nullable=True),
    sa.Column('last_edited', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_table('backups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('filepath', sa.VARCHAR(), nullable=False),
    sa.Column('backup_type', sa.VARCHAR(), nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_id'), 'backups', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=False),
    sa.Column('credits', sa.INTEGER(), nullable=True),
    sa.Column('faculty_name', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('students_enrolled', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=1)
    op.create_table('resume_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_skills_id'), 'resume_skills', ['id'], unique=False)
    op.create_table('download_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('format', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_logs_id'), 'download_logs', ['id'], unique=False)
    op.create_table('resume_ats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('overall_score', sa.INTEGER(), nullable=True),
    sa.Column('formatting_score', sa.INTEGER(), nullable=True),
    sa.Column('keyword_match', sa.INTEGER(), nullable=True),
    sa.Column('grammar_score', sa.INTEGER(), nullable=True),
    sa.Column('readability_score', sa.INTEGER(), nullable=True),
    sa.Column('recruiter_score', sa.INTEGER(), nullable=True),
    sa.Column('missing_keywords', sa.TEXT(), nullable=True),
    sa.Column('suggestions', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_ats_id'), 'resume_ats', ['id'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('browser', sa.VARCHAR(), nullable=True),
    sa.Column('device', sa.VARCHAR(), nullable=True),
    sa.Column('login_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('logout_time', sa.DATETIME(), nullable=True),
    sa.Column('login_status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_id'), 'login_history', ['id'], unique=False)
    op.create_table('resume_experience',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('company', sa.VARCHAR(), nullable=False),
    sa.Column('position', sa.VARCHAR(), nullable=False),
    sa.Column('duration', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('achievements', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_experience_id'), 'resume_experience', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('two_factor_secret', sa.VARCHAR(), nullable=True),
    sa.Column('force_logout', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=1)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=1)
    op.create_table('ai_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('feature', sa.VARCHAR(), nullable=False),
    sa.Column('provider_slug', sa.VARCHAR(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_id'), 'ai_models', ['id'], unique=False)
    op.create_index(op.f('ix_ai_models_feature'), 'ai_models', ['feature'], unique=1)
    op.create_table('activity_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('activity', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('resume_downloads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('format', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_downloads_id'), 'resume_downloads', ['id'], unique=False)
    op.create_table('resume_master',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('resume_type', sa.VARCHAR(), nullable=True),
    sa.Column('target_role', sa.VARCHAR(), nullable=True),
    sa.Column('career_objective', sa.TEXT(), nullable=True),
    sa.Column('preferred_industry', sa.VARCHAR(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('expected_salary', sa.VARCHAR(), nullable=True),
    sa.Column('visibility', sa.VARCHAR(), nullable=True),
    sa.Column('template_id', sa.VARCHAR(), nullable=True),
    sa.Column('color_theme', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('ats_score', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_master_id'), 'resume_master', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('roll_number', sa.VARCHAR(), nullable=False),
    sa.Column('student_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('dob', sa.VARCHAR(), nullable=False),
    sa.Column('department', sa.VARCHAR(), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=False),
    sa.Column('section', sa.VARCHAR(), nullable=True),
    sa.Column('academic_year', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('account_activated', sa.BOOLEAN(), nullable=True),
    sa.Column('otp_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=1)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('ai_providers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('encrypted_api_key', sa.VARCHAR(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('today_requests', sa.INTEGER(), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('success_rate', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_providers_slug'), 'ai_providers', ['slug'], unique=1)
    op.create_index(op.f('ix_ai_providers_name'), 'ai_providers', ['name'], unique=1)
    op.create_index(op.f('ix_ai_providers_id'), 'ai_providers', ['id'], unique=False)
    op.create_table('editing_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editing_sessions_id'), 'editing_sessions', ['id'], unique=False)
    op.create_table('resume_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('ats_rating', sa.INTEGER(), nullable=True),
    sa.Column('popularity', sa.INTEGER(), nullable=True),
    sa.Column('color_theme', sa.VARCHAR(), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_templates_slug'), 'resume_templates', ['slug'], unique=1)
    op.create_index(op.f('ix_resume_templates_id'), 'resume_templates', ['id'], unique=False)
    op.create_table('ai_gateway_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('feature', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('user_roll', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_gateway_logs_id'), 'ai_gateway_logs', ['id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recipient', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('scheduled_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('hod_name', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('student_count', sa.INTEGER(), nullable=True),
    sa.Column('subject_count', sa.INTEGER(), nullable=True),
    sa.Column('faculty_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=1)
    op.create_table('career_readiness',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=True),
    sa.Column('readiness_score', sa.INTEGER(), nullable=True),
    sa.Column('job_readiness', sa.VARCHAR(), nullable=True),
    sa.Column('skill_gap', sa.TEXT(), nullable=True),
    sa.Column('recommended_certifications', sa.TEXT(), nullable=True),
    sa.Column('recommended_projects', sa.TEXT(), nullable=True),
    sa.Column('recommended_courses', sa.TEXT(), nullable=True),
    sa.Column('interview_readiness', sa.INTEGER(), nullable=True),
    sa.Column('learning_roadmap', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_readiness_id'), 'career_readiness', ['id'], unique=False)
    op.create_table('ai_system_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('auto_retry', sa.BOOLEAN(), nullable=True),
    sa.Column('fallback', sa.BOOLEAN(), nullable=True),
    sa.Column('ai_timeout', sa.INTEGER(), nullable=True),
    sa.Column('request_limit', sa.INTEGER(), nullable=True),
    sa.Column('log_retention', sa.INTEGER(), nullable=True),
    sa.Column('debug', sa.BOOLEAN(), nullable=True),
    sa.Column('jwt_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('https_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('rate_limit_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('firewall_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('validation_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('xss_protected', sa.BOOLEAN(), nullable=True),
    sa.Column('sql_injection_protected', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_system_settings_id'), 'ai_system_settings', ['id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=1)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_table('ai_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('feature', sa.VARCHAR(), nullable=False),
    sa.Column('prompt_text', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prompts_id'), 'ai_prompts', ['id'], unique=False)
    op.create_index(op.f('ix_ai_prompts_feature'), 'ai_prompts', ['feature'], unique=1)
    # ### end Alembic commands ###
